language: python
dist: xenial
os: linux
script:
  - bash tests/list_tests.sh
  - bash tests/spider_test.sh regional
  - bash tests/spider_test.sh hkoforecast
  - bash tests/spider_test.sh hko9dayforecast
after_success:
  - bash <(curl -s https://codecov.io/bash)
