name: hk0weather-tests
on: [push]
jobs:
  do-hk0weather-tests:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Tests Scrapers
        run: |
          pip install -r requirements.txt
          coverage run -m scrapy list
          coverage run -m scrapy crawl regional -t csv -o regional.csv
          coverage run -m scrapy crawl hkoforecast -t csv -o hkoforecast.csv
          coverage run -m scrapy crawl hko9dayforecast -t csv -o hko9dayforecast.csv
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
